/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package fil;

import com.nitgen.SDK.BSP.NBioBSPJNI;
import java.io.BufferedOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Blob;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

/**
 *
 * @author iith
 */
public class verification extends javax.swing.JFrame {

    /**
     * Creates new form verification
     */
    public  static Boolean bResult;
    public verification() {
          bResult = new Boolean(false);
        this.setTitle("Verification....");
         // initComponents();
          //jButton2.setVisible(false);
          bsp = new NBioBSPJNI();
                      if (CheckError())
                      return ;
                       exportEngine = bsp.new Export();
                        if (CheckError())
                         return ;

        //setTitle("NBioAPI_WSQDemo BSP version: " + bsp.GetVersion());

               bsp.OpenDevice();
 
               if (CheckError())
                   return ;
     initComponents();
    }

     public void dispose()
    {
        if (hWSQFIR1 != null)  {
            hWSQFIR1.dispose();
            hWSQFIR1 = null;
        }

        if (hWSQFIR2 != null)  {
            hWSQFIR2.dispose();
            hWSQFIR2 = null;
        }

        if (bsp != null) {
            bsp.CloseDevice();
            bsp.dispose();
            bsp = null;
        }
    }

    public void Closing()
    {
        dispose();
    }

    private Boolean CheckError()
    {
        if (bsp.IsErrorOccured())  {
            javax.swing.JOptionPane.showMessageDialog(null, "NBioBSP Error Occured [" + bsp.GetErrorCode() + "]");
            return true;
        }

        return false;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Capture");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("verifymatch in databas");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(146, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        // TODO add your handling code here:
        
         //NBioBSPJNI.FIR_HANDLE hSavedFIR;
       //  NBioBSPJNI.FIR_HANDLE hSavedAuditFIR;

        /// hSavedFIR = bsp.new FIR_HANDLE();
       //  hSavedAuditFIR = bsp.new FIR_HANDLE();
         hWSQFIR1= bsp.new FIR_HANDLE();
         bsp.Capture(hWSQFIR1);

        if (CheckError())
            return ;
        //  if (hWSQFIR1 != null)  {
          //  NBioBSPJNI.INPUT_FIR inputFIR = bsp.new INPUT_FIR();
          //  inputFIR.SetFIRHandle(hWSQFIR1);
           // bsp.Process(inputFIR, hWSQFIR1);

           /* NBioBSPJNI.Export.AUDIT exportAudit = exportEngine.new AUDIT();

            exportEngine.ExportAudit(inputFIR, exportAudit);

            if (CheckError())
                return ;

            float fQuality = 0.7f;

            if (SaveWSQData != null)
                SaveWSQData = null;

            SaveWSQData = exportEngine.new TEMPLATE_DATA();
            exportEngine.ConvertRawToWsq(exportAudit.FingerData[0].Template[0].Data , exportAudit.ImageWidth, exportAudit.ImageHeight, SaveWSQData, fQuality);

            if (CheckError())
                return ;*/

          
          javax.swing.JOptionPane.showMessageDialog(null, "Make WSQ Data Success");
     //     jButton2.setEnabled(true); 
        
    }//GEN-LAST:event_jButton1ActionPerformed
    
    
   // }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
               try {
		Class.forName("com.mysql.jdbc.Driver");
	} catch (ClassNotFoundException e) {
		System.out.println("Where is your MySQL JDBC Driver?");
		e.printStackTrace();
	}
 
            Connection con = null;
 
	try 
        {
		con = DriverManager
		.getConnection("jdbc:mysql://localhost:3306/mysql","root","root");
 
	} catch (SQLException e) {
		System.out.println("Connection Failed! Check output console");
		e.printStackTrace();
	}
 
	//Statements allow to issue SQL queries to the database
       
        try{
        Statement statement = con.createStatement();
        // Result set get the result of the SQL query
        ResultSet resultSet = statement.executeQuery("select * from reg");

        while (resultSet.next()) 
         {  //retrieve data
          
           try
          {
             Blob b=resultSet.getBlob(5); 
             InputStream  inputstream = b.getBinaryStream();
             saveDatabaseFileToFileSystem(inputstream);
             byte[] loadData;
             int nLoadLen = 0;
           
            //   try
             //  {
                File f1=new File("D:\\sample\\27.wsq");
                FileInputStream fis =new FileInputStream(f1);
                long nFileLen = f1.length();
                loadData = new byte[(int) nFileLen];
                nLoadLen = fis.read(loadData);
                if (nLoadLen > 0)  {
                   
               NBioBSPJNI.Export.AUDIT exportAudit = exportEngine.new AUDIT();
               NBioBSPJNI.FIR_HANDLE hAudtiFIR;
                   
                exportEngine.ConvertWsqToRaw(loadData, nLoadLen, exportAudit);
                System.out.println("ok");
                f1.deleteOnExit();
                System.out.println("ok");  
                if (CheckError())
                   return ;

               // if (hWSQFIR1 != null)  {
                   // hWSQFIR1.dispose();
                    //hWSQFIR1 = null;
              //  }

                hAudtiFIR = bsp.new FIR_HANDLE();

                exportEngine.ImportAudit(exportAudit, hAudtiFIR);
                 
               
                if (CheckError())
                    return ;

                NBioBSPJNI.INPUT_FIR inputFIR = bsp.new INPUT_FIR();

                inputFIR.SetFIRHandle(hAudtiFIR);
                hWSQFIR2 = bsp.new FIR_HANDLE();

                bsp.Process(inputFIR,hWSQFIR2);

                if (CheckError())
                    return ;
                 
               if (hWSQFIR2!=null&&hWSQFIR1!=null)  
               {
                 NBioBSPJNI.INPUT_FIR inputFIR11 = bsp.new INPUT_FIR();
                 NBioBSPJNI.INPUT_FIR inputFIR22 = bsp.new INPUT_FIR();
                 inputFIR11.SetFIRHandle(hWSQFIR1);
                 inputFIR22.SetFIRHandle(hWSQFIR2);
                 System.out.println("kkkkkk");  
                 bsp.VerifyMatch(inputFIR22,inputFIR11,bResult, null);
                 System.out.println("kkkkkk");
        if (CheckError())
            return ;
        System.out.println("kkkkkk");
       if(exportAudit!=null)
                   {
                       exportAudit=null;
                       inputFIR11=null;
                       inputFIR22=null;
                       loadData=null;
                       nLoadLen=0;
                       hAudtiFIR=null;
                       fis.close();
                       //System.gc();
                   }
        
        if (bResult)
        {
           System.out.println("matched...");
            //javax.swing.JOptionPane.showMessageDialog(null, "Verify OK");
            return;
        
        }else
           // javax.swing.JOptionPane.showMessageDialog(null, "Verify Failed");
        {          
        
            System.out.println("failed....");
            if     (hWSQFIR2 != null)  {
                    hWSQFIR2.dispose();
                    hWSQFIR2 = null;
               }
       
        }
        //    btnMatch.setEnabled(true);
            //    }

             //   javax.swing.JOptionPane.showMessageDialog(null, "Make FIR Handle Success");
               }}
            } catch(IOException e)
                   
           {}
         
         
         
         }}catch(SQLException e)
         {
             
         }
            /*    byte[] loadData;
                int nLoadLen = 0;
           
            try{
           
                File f1=new File("C:\\Users\\iith\\Desktop\\hanuman\\27.wsq");
                FileInputStream fis =new FileInputStream(f1);
                long nFileLen = f1.length();
                loadData = new byte[(int) nFileLen];
                nLoadLen = fis.read(loadData);
                if (nLoadLen > 0)  {
                NBioBSPJNI.Export.AUDIT exportAudit = exportEngine.new AUDIT();
                NBioBSPJNI.FIR_HANDLE hAudtiFIR;

                exportEngine.ConvertWsqToRaw(loadData, nLoadLen, exportAudit);

                if (CheckError())
                    return ;

                if (hWSQFIR1 != null)  {
                    hWSQFIR1.dispose();
                    hWSQFIR1 = null;
                }

                hAudtiFIR = bsp.new FIR_HANDLE();

                exportEngine.ImportAudit(exportAudit, hAudtiFIR);

                if (CheckError())
                    return ;

                NBioBSPJNI.INPUT_FIR inputFIR = bsp.new INPUT_FIR();

                inputFIR.SetFIRHandle(hAudtiFIR);
                hWSQFIR1 = bsp.new FIR_HANDLE();

                bsp.Process(inputFIR, hWSQFIR1);

                if (CheckError())
                    return ;

                if (hWSQFIR2 != null)  {
                    btnMatch.setEnabled(true);
                }

                javax.swing.JOptionPane.showMessageDialog(null, "Make FIR Handle Success");
            }
            } catch(IOException e)
                   
           {}*/
            
          /* long nFileLen = fs.getSelectedFile().length();

            loadData = new byte[(int) nFileLen];

            try  {
                fis = new java.io.FileInputStream(fs.getSelectedFile());

                java.io.File fp = fs.getSelectedFile();

                nLoadLen = fis.read(loadData);
            }
            catch (Exception e)  {
                javax.swing.JOptionPane.showMessageDialog(null, "FIle IO Error!!");
                return ;
            }
            finally  {
                try  {
                    fis.close();
                }
                catch (java.io.IOException e)
                {
                    javax.swing.JOptionPane.showMessageDialog(null, "FIle IO Error!!");
                    return ;
                }
            }*/

            
           // else
              //  javax.swing.JOptionPane.showMessageDialog(null, "File load fail");
        //}
    }                                        
private void saveDatabaseFileToFileSystem(InputStream bis) {
        try {
            //now = Calendar.getInstance();
            bos = new BufferedOutputStream(new FileOutputStream("D:\\sample\\27.wsq"));
            writebuffer = new byte[100000];
            int read = 0;
            while ((read = bis.read(writebuffer)) > 0) {
                bos.write(writebuffer, 0, read);
            }
                 bos.flush();
           // saveToDataBase(bis);
            //count++;
            System.out.println("database file transfer success");
        } catch (IOException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        } finally {
            try {
               
                bos.close();
                //bis.close();
            } catch (IOException e) {
                // TODO Auto-generated catch block
                e.printStackTrace();
            }

        }

      
        
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(verification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(verification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(verification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(verification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new verification().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    // End of variables declaration//GEN-END:variables
        NBioBSPJNI     bsp;
        NBioBSPJNI.Export   exportEngine;
        NBioBSPJNI.Export.TEMPLATE_DATA  SaveWSQData;
        NBioBSPJNI.FIR_HANDLE   hWSQFIR1;
        NBioBSPJNI.FIR_HANDLE hWSQFIR2;
        byte[] writebuffer;
        FileInputStream fis;
        BufferedOutputStream  bos; 
        PreparedStatement pre;
     
}
